Updated to fix bugs when running in docker

diff --git a/login_wireguard_server b/login_wireguard_server
--- a/login_wireguard_server
+++ b/login_wireguard_server
@@ -1,11 +1,12 @@
 #!/bin/bash -ue
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 CREDS_FILE="${CREDS_FILE:-"creds.env"}"
 [ -f "$CREDS_FILE" ] && source "$CREDS_FILE"
 [ -n "$PRIVADO_USERNAME" ] || { echo >&2 "ERROR: PRIVADO_USERNAME not set or missing creds file; exit 255; }
 [ -n "$PRIVADO_PASSWORD" ] || { echo >&2 "ERROR: PRIVADO_PASSWORD not set or missing creds file; exit 255; }
 CLIENT_API_URL="${CLIENT_API_URL:-"https://client-api.privado.io/v1"}"
 USER_AGENT="${USER_AGENT:-"App: 3.0.0 (576942783), macOS: Version 12.4 (Build 21F79)"}"
-PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"data"}"
+PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"$SCRIPT_DIR/data"}"
 LOGIN_TOKEN_FILE="${LOGIN_TOKEN:-"$PRIVADO_DATA_DIR/token.json"}"
 SERVERS_JSON="${SERVERS_JSON:-"$PRIVADO_DATA_DIR/servers.json"}"
 
@@ -14,12 +15,12 @@ command -v jq >/dev/null 2>&1 || { echo >&2 "I require jq but it's not installed
 
 SERVER_NAME="${1-}"
 SERVER_API_PORT="44121"
-[ -n "$SERVER_NAME" ] || { echo >&2 "ERROR: must pass server name to login to"; exit 255; }
+[ -n "$SERVER_NAME" ] || { echo >&2 "ERROR: must pass server name,city or country to login to"; exit 255; }
 if [ ! -s "$SERVERS_JSON" ]; then
   echo >&2 "ERROR: cannot find servers json $SERVERS_JSON, run get_servers first!"; exit 100
-elif ! grep -q "\"name\": \"$SERVER_NAME\"" "$SERVERS_JSON"; then
-  echo >&2 "ERROR: server '$SERVER_NAME' not found in $SERVERS_JSON list!"
 fi
+
+SERVER_NAME="$("$SCRIPT_DIR/resolve_server_name" "$SERVER_NAME")" || { echo >&2 "ERROR: cannot resolve server name"; exit 253; }
 
 RESULT="$(curl "https://${SERVER_NAME}:${SERVER_API_PORT}/api/1.0/login" \
 --compressed --silent \
@@ -44,4 +45,4 @@ fi
 RESULT="$(echo "$RESULT" | jq 'del(.Status)')"
 NEW_SERVER_CONTENT="$(jq -e --argjson result "$RESULT" '. += [$result]' "$WIREGUARD_KEYS_FILE")"
 echo "$NEW_SERVER_CONTENT" > "$WIREGUARD_KEYS_FILE"
-echo "Successfully got wireguard interface ip $WG_IP_ADDRESS for $SERVER_NAME"
+echo "Successfully got wireguard interface ip '$WG_IP_ADDRESS' for '$SERVER_NAME'"
diff --git a/logout_wireguard_server b/logout_wireguard_server
--- a/logout_wireguard_server
+++ b/logout_wireguard_server
@@ -1,11 +1,12 @@
 #!/bin/bash -u
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 CREDS_FILE="${CREDS_FILE:-"creds.env"}"
 [ -f "$CREDS_FILE" ] && source "$CREDS_FILE"
 SERVER_NAME="${1-}"
 SERVER_API_PORT="44121"
 WG_IP_ADDRESS="${2-}"
 WG_PUBLIC_KEY="${3-}"
-PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"data"}"
+PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"$SCRIPT_DIR/data"}"
 SERVERS_JSON="${SERVERS_JSON:-"$PRIVADO_DATA_DIR/servers.json"}"
 USER_AGENT="${USER_AGENT:-"App: 3.0.0 (576942783), macOS: Version 12.4 (Build 21F79)"}"
 #[ -n "$WG_IP_ADDRESS" ] || { echo >&2 "ERROR: must pass WG ip address to logout"; exit 255; }
@@ -25,6 +26,7 @@ elif ! jq -e --arg server_name "$SERVER_NAME" '.servers[] | select(.name == $ser
   echo >&2 "ERROR: $SERVER_NAME is not a valid server!"; exit 200
 fi
 WIREGUARD_KEYS_FILE="$PRIVADO_DATA_DIR/wg_${SERVER_NAME}.json"
+[ -f "$WIREGUARD_KEYS_FILE" ] || { echo >&2 "ERROR: no ips found for server $SERVER_NAME"; exit 255; }
 
 lookup_public_key() {
   WG_PUBLIC_KEY="$(jq -r --arg wg_ip_address "$1" '[.[] | select(.WGIPAddress == $wg_ip_address)][0] | .WGPublicKey' "$WIREGUARD_KEYS_FILE")"
diff --git a/wireguard_conf_start_to_finish b/wireguard_conf_start_to_finish
--- a/wireguard_conf_start_to_finish
+++ b/wireguard_conf_start_to_finish
@@ -1,15 +1,25 @@
 #!/bin/bash -u
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 CREDS_FILE="${CREDS_FILE:-"creds.env"}"
 [ -f "$CREDS_FILE" ] && source "$CREDS_FILE"
-PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"data"}"
+PRIVADO_DATA_DIR="${PRIVADO_DATA_DIR:-"$SCRIPT_DIR/data"}"
+LOGIN_TOKEN_FILE="${LOGIN_TOKEN:-"$PRIVADO_DATA_DIR/token.json"}"
+SERVERS_JSON="${SERVERS_JSON:-"$PRIVADO_DATA_DIR/servers.json"}"
 SERVER_NAME="${1-}"
-[ -n "$SERVER_NAME" ] || { echo >&2 "ERROR: must pass server name"; exit 255; }
+[ -n "$SERVER_NAME" ] || { echo >&2 "ERROR: must pass server name, city or country"; exit 255; }
 OUTPUT_FILE="${2-}"
 [ -n "$OUTPUT_FILE" ] || { echo >&2 "ERROR: must pass output file"; exit 255; }
 
-./login || { echo >&2 "ERROR: failed to login"; exit 99; }
-./get_servers || { echo >&2 "ERROR: failed to get servers"; exit 100; }
-./login_wireguard_server "$SERVER_NAME" || { echo >&2 "ERROR: failed to get wireguard ip"; exit 101; }
-WG_INTERFACE_IP="$(jq -r -e '.[-1].WGIPAddress' "$PRIVADO_DATA_DIR/wg_$SERVER_NAME.json")"
-./gen_wireguard_conf "$SERVER_NAME" "$WG_INTERFACE_IP" "$OUTPUT_FILE" || { echo >&2 "ERROR: failed to generate conf"; exit 102; }
+if [ ! -f "$SERVERS_JSON" ]; then
+  [ -f "$LOGIN_TOKEN_FILE" ] && echo "Found existing login token" || "$SCRIPT_DIR/login" 
+  RETCODE=$?; [ "$RETCODE" -eq 0 ] || { echo >&2 "ERROR: failed to login"; exit 99; }
+  "$SCRIPT_DIR/get_servers" || { echo >&2 "ERROR: failed to get servers"; exit 100; }
+else
+  echo "Found existing server list, no need to login"
+fi
+SERVER_NAME="$("$SCRIPT_DIR/resolve_server_name" "$SERVER_NAME")"
+RESULT="$("$SCRIPT_DIR/login_wireguard_server" "$SERVER_NAME")" || { echo >&2 "ERROR: failed to get wireguard ip"; exit 101; }
+echo "$RESULT"
+WG_INTERFACE_IP="$(echo "$RESULT" | cut -f2 -d"'")"
+"$SCRIPT_DIR/gen_wireguard_conf" "$SERVER_NAME" "$WG_INTERFACE_IP" "$OUTPUT_FILE" || { echo >&2 "ERROR: failed to generate conf"; exit 102; }
 exit 0
